'use strict';
const el=id=>document.getElementById(id);
const labels={max_trades_per_day:'Maximum entry attempts / day',max_contracts:'Maximum contracts / entry',risk_per_trade_inr:'Risk per trade · INR',daily_profit_inr:'Daily net profit stop · INR',daily_loss_inr:'Daily net loss stop · INR',quote_to_inr:'Quote USD → INR settlement conversion',fee_bps_per_side:'Fees + taxes per side · basis points',max_spread_bps:'Maximum bid/ask spread · basis points',max_slippage_bps:'Entry slippage cap · basis points'};
let state={},initialized=false,busy=false;
for(const [key,label] of Object.entries(labels)){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.id=key;input.type='number';input.min=['max_trades_per_day','max_contracts'].includes(key)?'1':'0.000001';input.step=['max_trades_per_day','max_contracts'].includes(key)?'1':'any';input.required=true;input.addEventListener('input',()=>{input.dataset.edited='1';});l.append(input);el('fields').append(l);}
const fmt=v=>v===null||v===undefined?'—':typeof v==='object'?JSON.stringify(v):String(v);
const num=v=>v===null||v===undefined?'—':Number(v).toLocaleString('en-IN',{maximumFractionDigits:4});
function table(id,rows,columns){const t=document.createElement('table'),head=document.createElement('thead'),hr=document.createElement('tr');for(const [name] of columns){const th=document.createElement('th');th.textContent=name;hr.append(th);}head.append(hr);t.append(head);const body=document.createElement('tbody');for(const row of rows||[]){const tr=document.createElement('tr');for(const [,key]of columns){const td=document.createElement('td');td.textContent=fmt(row[key]);tr.append(td);}body.append(tr);}if(!rows?.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=columns.length;td.className='empty';td.textContent='No records returned';tr.append(td);body.append(tr);}t.append(body);el(id).replaceChildren(t);}
async function request(url,payload){const response=await fetch(url,payload===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json','X-CRT-Control':'1'},body:JSON.stringify(payload)});if(response.status===401){location.assign('/auth/login');throw Error('Sign in required');}const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function render(s){state=s;el('engine-state').textContent=s.state;el('reason').textContent=s.reason;el('toggle').textContent=s.enabled?'Turn live entries OFF':'Turn live entries ON';el('toggle').classList.toggle('on',!!s.enabled);el('toggle').disabled=busy||(!s.enabled&&!s.live_permitted);el('updated').textContent=s.as_of?'Updated '+new Date(s.as_of*1000).toLocaleString():'Waiting for market data';el('pnl').textContent=num(s.daily_net_inr);el('count').textContent=(s.trades_today??0)+' / '+(s.risk_limits?.max_trades_per_day??'—');el('signal').textContent=s.signal?.side?.toUpperCase()||'WAITING';el('error').textContent=s.error||(!s.live_permitted?'Server live permission is OFF. Set CRT_LIVE_ENABLED=1 only when ready for real orders.':'');for(const key of Object.keys(labels)){const input=el(key),saved=s.risk_limits?.[key];if(saved!==null&&saved!==undefined&&!input.dataset.edited&&document.activeElement!==input)input.value=String(saved);input.disabled=!!s.enabled;}initialized=true;table('journal',s.intents,[['Setup ID','id'],['IST day','day'],['Submission state','state']]);draw();}
function draw(){const c=el('chart'),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=390;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const bars=state.candles||[];ctx.fillStyle='#93a7b9';ctx.font='12px system-ui';if(!bars.length){ctx.fillText('Waiting for verified Delta candles…',20,50);return;}const s=state.signal||{},extra=[s.stop,s.target].filter(Number.isFinite),low=Math.min(...bars.map(b=>b.low),...extra),high=Math.max(...bars.map(b=>b.high),...extra),pad=Math.max((high-low)*.08,.1),lo=low-pad,hi=high+pad,left=12,right=w-80,top=20,bottom=h-30,step=(right-left)/bars.length,x=i=>left+step*(i+.5),y=p=>bottom-(p-lo)/(hi-lo)*(bottom-top);ctx.strokeStyle='#253546';for(let i=0;i<=5;i++){const price=lo+(hi-lo)*i/5;ctx.beginPath();ctx.moveTo(left,y(price));ctx.lineTo(right,y(price));ctx.stroke();ctx.fillText(price.toFixed(2),right+8,y(price)+4);}if(s.reference){const i=bars.findIndex(b=>b.time===s.reference.time);ctx.fillStyle='#6e98ef20';ctx.fillRect(Math.max(left,x(i)-step/2),y(s.reference.high),right-Math.max(left,x(i)-step/2),y(s.reference.low)-y(s.reference.high));}bars.forEach((b,i)=>{ctx.strokeStyle=ctx.fillStyle=b.close>=b.open?'#58deb0':'#ff8391';ctx.beginPath();ctx.moveTo(x(i),y(b.high));ctx.lineTo(x(i),y(b.low));ctx.stroke();ctx.fillRect(x(i)-Math.max(1,step*.32),y(Math.max(b.open,b.close)),Math.max(2,step*.64),Math.max(1,Math.abs(y(b.close)-y(b.open))));if(b.time===s.sweep?.time){ctx.fillStyle='#c5acff';ctx.fillText('◆',x(i)-5,y(b.high)-7);}});for(const [key,label,color]of[['stop','SL','#ff8391'],['target','TP','#58deb0'],['entry','ENTRY','#aebef5']]){if(!Number.isFinite(s[key]))continue;ctx.strokeStyle=color;ctx.setLineDash([5,4]);ctx.beginPath();ctx.moveTo(left,y(s[key]));ctx.lineTo(right,y(s[key]));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.fillText(label,right-45,y(s[key])-5);}ctx.fillStyle='#93a7b9';[0,Math.floor(bars.length/2),bars.length-1].forEach(i=>ctx.fillText(new Date(bars[i].time*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),Math.min(x(i),right-40),h-6));el('levels').textContent='Range: '+num(s.reference?.low)+' – '+num(s.reference?.high)+' · Stop: '+num(s.stop)+' · Target: '+num(s.target);}
async function refreshAccount(){try{const d=await request('/api/snapshot');el('connection').textContent=d.connection.toUpperCase();el('balance').textContent=d.wallets.map(w=>num(w.balance)+' '+w.asset_symbol).join(' / ')||'—';el('available').textContent=d.wallets.map(w=>num(w.available_balance)+' '+w.asset_symbol).join(' / ')||'—';table('positions',d.positions,[['Product','product_symbol'],['Size','size'],['Entry','entry_price'],['Mark','mark_price'],['Realized','realized_pnl'],['Unrealized','unrealized_pnl']]);table('orders',d.open_orders,[['Product','product_symbol'],['Side','side'],['Size','size'],['Type','order_type'],['Stop','stop_price'],['State','state']]);table('fills',d.fills,[['Time','created_at'],['Product','product_symbol'],['Side','side'],['Size','size'],['Price','price'],['Commission','commission']]);table('transactions',d.transactions,[['Time','created_at'],['Type','transaction_type'],['Asset','asset_symbol'],['Amount','amount']]);}catch(e){el('connection').textContent='UNAVAILABLE';el('error').textContent=e.message;}}
el('toggle').onclick=async()=>{busy=true;try{render(await request('/api/crt/toggle',{enabled:!state.enabled}));}catch(e){el('error').textContent=e.message;}finally{busy=false;el('toggle').disabled=!state.enabled&&!state.live_permitted;}};
el('limits').onsubmit=async e=>{e.preventDefault();try{const values=Object.fromEntries(Object.keys(labels).map(k=>[k,Number(el(k).value)]));const saved=await request('/api/crt/limits',values);for(const key of Object.keys(labels))delete el(key).dataset.edited;render(saved);el('saved').textContent='Saved';}catch(err){el('saved').textContent=err.message;}};
async function poll(){try{render(await request('/api/crt'));}catch(e){el('error').textContent=e.message;}setTimeout(poll,5000);}
window.addEventListener('resize',draw);poll();refreshAccount();setInterval(refreshAccount,30000);
